code --install-extension aaron-bond.better-comments
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension enkia.tokyo-night
code --install-extension mikestead.dotenv
code --install-extension ms-vscode.atom-keybindings
code --install-extension naumovs.color-highlight
code --install-extension pflannery.vscode-versionlens
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension riccardoNovaglia.missinglineendoffile
code --install-extension salesforce.salesforcedx-vscode
code --install-extension salesforce.salesforcedx-vscode-apex
code --install-extension salesforce.salesforcedx-vscode-apex-debugger
code --install-extension salesforce.salesforcedx-vscode-apex-replay-debugger
code --install-extension salesforce.salesforcedx-vscode-core
code --install-extension salesforce.salesforcedx-vscode-lightning
code --install-extension salesforce.salesforcedx-vscode-lwc
code --install-extension salesforce.salesforcedx-vscode-visualforce
code --install-extension SirTori.indenticator
code --install-extension slevesque.vscode-multiclip
code --install-extension spywhere.guides
code --install-extension stevencl.addDocComments
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
